# Generated by Django 3.2.15 on 2023-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230514_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='Total_amount',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='productitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
