# Generated by Django 3.2.15 on 2023-05-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230530_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='ne_total_price',
            new_name='new_total_price',
        ),
    ]
