# Generated by Django 3.2.15 on 2023-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_ne_total_price_productitem_new_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='new_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='new_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
