# Generated by Django 3.2.15 on 2023-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230530_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
