# Generated by Django 3.2.15 on 2023-05-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='new_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
