# Generated by Django 3.2.15 on 2023-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productitem_new_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='new_quantity',
            field=models.IntegerField(default=models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='new_total_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=100), max_digits=100),
        ),
    ]
