# Generated by Django 3.2.15 on 2023-05-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
