# Generated by Django 3.2.15 on 2023-06-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
