# Generated by Django 3.2.15 on 2023-06-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productitem_new_total_price'),
        ('debts', '0004_debt_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='debt_sales', to='products.ProductItem'),
        ),
    ]
