# Generated by Django 3.2.15 on 2023-06-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_debt_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='productsid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
