# Generated by Django 3.2.15 on 2023-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_debt_productsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='products',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='productsid',
        ),
        migrations.AddField(
            model_name='debt',
            name='paid',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20, null=True),
        ),
    ]
