# Generated by Django 3.2.15 on 2023-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_productitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('products', models.ManyToManyField(related_name='products', to='products.ProductItem')),
            ],
        ),
    ]
