# Generated by Django 3.2.15 on 2023-05-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iventory',
            name='new_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='iventory',
            name='new_total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
