# Generated by Django 3.2.15 on 2023-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230530_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventory',
            name='new_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='iventory',
            name='new_total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
