# Generated by Django 3.2.15 on 2023-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20230530_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventory',
            name='new_total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='iventory',
            name='new_total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
