# Generated by Django 3.2.15 on 2023-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
