# Generated by Django 3.2.15 on 2023-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='created',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='sales',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
