# Generated by Django 3.2.15 on 2023-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20230529_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='debt',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=20, null=True),
        ),
    ]
