# Generated by Django 3.2.15 on 2023-05-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230530_1854'),
        ('sales', '0005_sales_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='invetory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.iventory'),
        ),
    ]
