# Generated by Django 3.2.15 on 2023-05-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_invetory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
